# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/data/accesorios.csv', 'data'),
        ('src/data/constantes.csv', 'data'),
        ('src/data/fluidos.csv', 'data'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtWidgets', 
        'PyQt6.QtGui',
        'PyQt6.QtCore.Qt',
        'PyQt6.QtWidgets.QApplication',
        'PyQt6.QtWidgets.QMainWindow',
        'PyQt6.QtWidgets.QWidget',
        'PyQt6.QtWidgets.QVBoxLayout',
        'PyQt6.QtWidgets.QHBoxLayout',
        'PyQt6.QtWidgets.QLabel',
        'PyQt6.QtWidgets.QPushButton',
        'PyQt6.QtWidgets.QGroupBox',
        'PyQt6.QtWidgets.QLineEdit',
        'PyQt6.QtWidgets.QDoubleSpinBox',
        'PyQt6.QtWidgets.QSpinBox',
        'PyQt6.QtWidgets.QComboBox',
        'PyQt6.QtWidgets.QCheckBox',
        'PyQt6.QtWidgets.QScrollArea',
        'PyQt6.QtWidgets.QTabWidget',
        'PyQt6.QtWidgets.QTableWidget',
        'PyQt6.QtWidgets.QHeaderView',
        'PyQt6.QtWidgets.QSplitter',
        'PyQt6.QtWidgets.QStatusBar',
        'PyQt6.QtWidgets.QMenuBar',
        'PyQt6.QtWidgets.QMessageBox',
        'PyQt6.QtWidgets.QGraphicsView',
        'PyQt6.QtWidgets.QGraphicsScene',
        'PyQt6.QtWidgets.QGraphicsItem',
        'PyQt6.QtWidgets.QGraphicsRectItem',
        'PyQt6.QtWidgets.QGraphicsEllipseItem',
        'PyQt6.QtWidgets.QGraphicsTextItem',
        'PyQt6.QtWidgets.QGraphicsLineItem',
        'PyQt6.QtWidgets.QGraphicsPolygonItem',
        'PyQt6.QtCore.pyqtSignal',
        'PyQt6.QtCore.QPointF',
        'PyQt6.QtGui.QPen',
        'PyQt6.QtGui.QBrush',
        'PyQt6.QtGui.QColor',
        'PyQt6.QtGui.QFont',
        'PyQt6.QtGui.QPainter',
        'PyQt6.QtGui.QPolygonF',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SistemaBombeo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SistemaBombeo',
)
